In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
#export

import random
import pandas as pd
import numpy as np


def shuffle_dataset(n, s=30, ratial=80):
    start_valid = int((n / 100) * ratial)
    random.seed(s)
    xs = list(range(n))
    random.seed(30)
    random.shuffle(xs)
    return xs[:start_valid], xs[start_valid:]

def load_data(preprocessors=[], keep_df=False):
    random.seed(30)
    X = pd.read_csv('data/train.csv')
    for preprocessor in preprocessors:
        X = preprocessor(X)
    train_ids, valid_ids = shuffle_dataset(len(X))
    if keep_df:
        test_df = pd.read_csv('data/test.csv')
        return X, test_df
    Y = X[['label']]
    del X['label']
    train_X, train_Y = X.iloc[train_ids], Y.iloc[train_ids]
    valid_X, valid_Y = X.iloc[valid_ids], Y.iloc[valid_ids]
    return train_X, train_Y, valid_X, valid_Y

In [3]:
train_X, train_Y, valid_X, valid_Y = load_data()
len(train_X), len(train_Y), len(valid_X), len(valid_Y)

/home/vule/miniconda3/envs/thanos/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3214: DtypeWarning: Columns (51) have mixed types. Specify dtype option on import or set low_memory=False.
  if (yield from self.run_code(code, result)):

(24000, 24000, 6000, 6000)

In [4]:
train_X.sample(3)

,id,province,district,age_source1,age_source2,maCv,FIELD_1,FIELD_2,FIELD_3,FIELD_4,...,FIELD_48,FIELD_49,FIELD_50,FIELD_51,FIELD_52,FIELD_53,FIELD_54,FIELD_55,FIELD_56,FIELD_57
12298,12298,Tỉnh An Giang,Huyện Phú Tân,57.0,57.0,None,1,1.0,2545.0,4.0,...,True,True,63.293,4.413,30.955,31.171,0.25,0.00,0.0,0.0
11974,11974,Tỉnh Tiền Giang,Huyện Cái Bè,37.0,37.0,Công Nhân Mài Chuẩn Bị,1,1.0,2540.0,0.0,...,True,True,29.770,61.314,30.955,31.171,0.00,0.19,0.0,0.0
16733,16733,Tỉnh Đồng Nai,Huyện Cẩm Mỹ,28.0,28.0,Công nhân,1,1.0,4012.0,2.0,...,True,True,29.770,59.867,30.955,31.171,0.00,0.18,0.0,0.0

### Do some stats

In [5]:
from collections import Counter

def stats(df):
    xs = df[df.notna()]
    c = df.columns[0]
    print(f"min: {xs.min()[c]}, max: {xs.max()[c]}, mean {xs.mean()[c]}, median {xs.median()[c]}, std {xs.std()[c]}")
    
def stats_df(df):
    for c in df.columns:
        stats = Counter(df[c])
        print(f"{c}: {len(stats)} elements, tops 4: {stats.most_common(4)}")

In [6]:
train_X

,id,province,district,age_source1,age_source2,maCv,FIELD_1,FIELD_2,FIELD_3,FIELD_4,...,FIELD_48,FIELD_49,FIELD_50,FIELD_51,FIELD_52,FIELD_53,FIELD_54,FIELD_55,FIELD_56,FIELD_57
25383,25383,NaN,NaN,NaN,NaN,NaN,0,0.0,-1.0,0.0,...,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7308,7308,NaN,NaN,NaN,23.0,None,1,1.0,1073.0,0.0,...,True,True,29.77,44.098,30.955,31.171,0.0,0.14,0.00,0.00
6149,6149,NaN,NaN,NaN,53.0,None,1,0.0,-1.0,0.0,...,False,True,29.77,11.102,30.955,31.171,0.0,0.03,0.00,0.00
2220,2220,NaN,NaN,NaN,28.0,nhân viên,1,1.0,1080.0,0.0,...,False,True,29.77,45.303,30.955,31.171,0.0,0.14,0.00,0.00
14015,14015,NaN,NaN,NaN,NaN,NaN,1,1.0,363.0,0.0,...,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27199,27199,Thành phố Hồ Chí Minh,Quận Thủ Đức,28.0,28.0,Nhân viên,1,1.0,2900.0,1.0,...,True,True,29.77,66.268,30.955,31.171,0.0,0.30,0.00,0.00
4790,4790,Tỉnh Thanh Hóa,Huyện Hà Trung,30.0,30.0,None,1,1.0,2191.0,0.0,...,True,False,29.77,31.170,30.955,31.171,0.0,0.10,0.00,0.00
29755,29755,NaN,NaN,NaN,NaN,NaN,1,1.0,3994.0,0.0,...,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28254,28254,NaN,NaN,NaN,21.0,None,0,0.0,-1.0,0.0,...,False,True,29.77,17.561,63.607,63.591,0.0,0.04,0.05,0.05
10173,10173,Thành phố Hải Phòng,Quận Ngô Quyền,50.0,50.0,None,1,0.0,-1.0,3.0,...,False,True,29.77,21.478,30.955,31.171,0.0,0.05,0.00,0.00

In [7]:
# stats_df(train_X)

In [8]:
class DataBunch():
    def __init__(self, train_X, train_Y, valid_X, valid_Y):
        self.train_X, self.train_Y, self.valid_X, self.valid_Y = train_X, train_Y, valid_X, valid_Y
        self.assets = {}
        self.train_X = self.filling_na(self.train_X)
    def add_asset(self, k,v):
        self.assets[k] = v

    def filling_na(self, df):
        df = self._preprocess_FIELD_3(df)
        df = self._preprocess_FIELD_7(df)
        fillan_unknown_list = ['province', 'district', 'maCv', 'FIELD_1', 'FIELD_2', 'FIELD_4',
                               'FIELD_5', 'FIELD_6', 'FIELD_8', 'FIELD_9',
                               'FIELD_10', 'FIELD_11', 'FIELD_12', 'FIELD_13', 'FIELD_14', 'FIELD_15',
                              'FIELD_16', 'FIELD_17', 'FIELD_18', 'FIELD_19', 'FIELD_20', 'FIELD_21',
                              'FIELD_23', 'FIELD_24', 'FIELD_25', 'FIELD_26', 'FIELD_27', 'FIELD_28',
                              'FIELD_29', 'FIELD_30', 'FIELD_31', 'FIELD_32', 'FIELD_33', 'FIELD_34',
                              'FIELD_35', 'FIELD_36', 'FIELD_37', 'FIELD_38', 'FIELD_39', 'FIELD_40', 'FIELD_41',
                              'FIELD_42', 'FIELD_43', 'FIELD_44', 'FIELD_45', 'FIELD_46', 'FIELD_47',
                               'FIELD_48', 'FIELD_49', 'FIELD_50']
        fillan_median_list = ['age_source1', 'age_source2',
                              'FIELD_22', 'FIELD_51', 'FIELD_52', 'FIELD_53', 'FIELD_54', 'FIELD_55', 'FIELD_56', 'FIELD_57']
        df = self._fillna_unknown(df, fillan_unknown_list)
        df = self._fillna_median(df, fillan_median_list)
        return df
    
    def _fillna_median(self, df, columns):
        for c in columns:
            if c not in self.assets:
                median = df[[c]].median()[c]
                self.add_asset(c, median)
            df[[c]] = df[[c]].fillna(self.assets[c])
            stats(df[[c]])
        return df
    
    def _fillna_unknown(self, df, columns):
        for c in columns:
            if c not in self.assets:
                self.add_asset(c, 'unknown')
            df[[c]] = df[[c]].fillna(self.assets[c])
            stats_df(df[[c]])
        return df
    
    def _preprocess_FIELD_3(self, df, mode='-1'):
        c = 'FIELD_3'
        if c not in self.assets:
            if mode == '-1':
                self.add_asset(c, -1)

        df[[c]] = df[[c]].fillna(self.assets[c])
        stats(df[[c]])
        return df
    
    def _preprocess_FIELD_7(self, df):
        c = 'FIELD_7'
        if c not in self.assets:
            self.add_asset(c, [])
        df[[c]] = df[[c]].fillna(0)
        df[c] = df[c].apply(lambda x: x if x else [])
        return df

In [9]:
train_X.columns

Index(['id', 'province', 'district', 'age_source1', 'age_source2', 'maCv',
       'FIELD_1', 'FIELD_2', 'FIELD_3', 'FIELD_4', 'FIELD_5', 'FIELD_6',
       'FIELD_7', 'FIELD_8', 'FIELD_9', 'FIELD_10', 'FIELD_11', 'FIELD_12',
       'FIELD_13', 'FIELD_14', 'FIELD_15', 'FIELD_16', 'FIELD_17', 'FIELD_18',
       'FIELD_19', 'FIELD_20', 'FIELD_21', 'FIELD_22', 'FIELD_23', 'FIELD_24',
       'FIELD_25', 'FIELD_26', 'FIELD_27', 'FIELD_28', 'FIELD_29', 'FIELD_30',
       'FIELD_31', 'FIELD_32', 'FIELD_33', 'FIELD_34', 'FIELD_35', 'FIELD_36',
       'FIELD_37', 'FIELD_38', 'FIELD_39', 'FIELD_40', 'FIELD_41', 'FIELD_42',
       'FIELD_43', 'FIELD_44', 'FIELD_45', 'FIELD_46', 'FIELD_47', 'FIELD_48',
       'FIELD_49', 'FIELD_50', 'FIELD_51', 'FIELD_52', 'FIELD_53', 'FIELD_54',
       'FIELD_55', 'FIELD_56', 'FIELD_57'],
      dtype='object')

In [10]:
db = DataBunch(*load_data())

min: -1.0, max: 8037.0, mean 1696.04775, median 1446.0, std 1473.9720286924098
province: 66 elements, tops 4: [('unknown', 10320), ('Thành phố Hồ Chí Minh', 1887), ('Tỉnh Đồng Nai', 797), ('Tỉnh Bình Dương', 637)]
district: 702 elements, tops 4: [('unknown', 10343), ('Huyện Châu Thành', 339), ('Thành phố Biên Hòa', 247), ('Thị xã Thuận An', 187)]
maCv: 2547 elements, tops 4: [('None', 10532), ('unknown', 7763), ('Công nhân', 612), ('công nhân', 364)]
FIELD_1: 2 elements, tops 4: [(1, 18601), (0, 5399)]
FIELD_2: 3 elements, tops 4: [(1.0, 18030), (0.0, 5589), ('unknown', 381)]
FIELD_4: 11 elements, tops 4: [(0.0, 15810), (1.0, 3821), (2.0, 2796), (3.0, 823)]
FIELD_5: 16 elements, tops 4: [(0.0, 9937), (2.0, 3722), (3.0, 2685), (1.0, 2449)]
FIELD_6: 6 elements, tops 4: [(0.0, 21136), (1.0, 1701), (2.0, 719), ('unknown', 381)]
FIELD_8: 3 elements, tops 4: [('MALE', 8777), ('unknown', 7762), ('FEMALE', 7461)]
FIELD_9: 35 elements, tops 4: [('DN', 8803), ('na', 7762), ('GD', 3875), ('TN', 839)]
FIELD_10: 3 elements, tops 4: [('T1', 8665), ('unknown', 7762), ('GH', 7573)]
FIELD_11: 42 elements, tops 4: [('unknown', 7762), ('12', 6818), ('0', 4411), ('6', 1683)]
FIELD_12: 6 elements, tops 4: [('0', 13275), ('unknown', 7762), ('None', 2900), ('1', 61)]
FIELD_13: 210 elements, tops 4: [('unknown', 7784), ('YN', 3970), ('BI', 3876), ('TA', 959)]
FIELD_14: 2 elements, tops 4: [(0, 14423), (1, 9577)]
FIELD_15: 2 elements, tops 4: [(0, 14489), (1, 9511)]
FIELD_16: 6 elements, tops 4: [(1.0, 14721), ('unknown', 7762), (2.0, 1357), (3.0, 135)]
FIELD_17: 9 elements, tops 4: [('None', 13250), ('unknown', 7762), ('G8', 2866), ('G3', 62)]
FIELD_18: 3 elements, tops 4: [(True, 9210), ('unknown', 7762), (False, 7028)]
FIELD_19: 3 elements, tops 4: [(False, 12207), ('unknown', 7762), (True, 4031)]
FIELD_20: 3 elements, tops 4: [(False, 13707), ('unknown', 7762), (True, 2531)]
FIELD_21: 4 elements, tops 4: [(1.0, 16217), ('unknown', 7762), (2.0, 13), (0.0, 8)]
FIELD_23: 2 elements, tops 4: [(True, 16238), ('unknown', 7762)]
FIELD_24: 5 elements, tops 4: [('None', 15837), ('unknown', 7762), ('K2', 178), ('K1', 133)]
FIELD_25: 3 elements, tops 4: [(True, 12656), ('unknown', 7762), (False, 3582)]
FIELD_26: 3 elements, tops 4: [(False, 9817), ('unknown', 7762), (True, 6421)]
FIELD_27: 3 elements, tops 4: [(True, 16083), ('unknown', 7762), (False, 155)]
FIELD_28: 3 elements, tops 4: [(True, 16082), ('unknown', 7762), (False, 156)]
FIELD_29: 4 elements, tops 4: [('FALSE', 13332), ('unknown', 7762), ('None', 2905), ('TRUE', 1)]
FIELD_30: 4 elements, tops 4: [('FALSE', 8405), ('unknown', 7762), ('TRUE', 4506), ('None', 3327)]
FIELD_31: 3 elements, tops 4: [('FALSE', 12821), ('unknown', 7762), ('None', 3417)]
FIELD_32: 2 elements, tops 4: [(0, 15879), (1, 8121)]
FIELD_33: 2 elements, tops 4: [(1, 16410), (0, 7590)]
FIELD_34: 2 elements, tops 4: [(0, 13046), (1, 10954)]
FIELD_35: 6 elements, tops 4: [('unknown', 7762), ('Zero', 7338), ('One', 3595), ('Four', 3238)]
FIELD_36: 4 elements, tops 4: [('FALSE', 12698), ('unknown', 7762), ('TRUE', 3535), ('None', 5)]
FIELD_37: 6 elements, tops 4: [(True, 8343), ('unknown', 7762), ('TRUE', 6893), (False, 552)]
FIELD_38: 3 elements, tops 4: [(False, 16138), ('unknown', 7762), (True, 100)]
FIELD_39: 45 elements, tops 4: [('VN', 8466), ('unknown', 7762), ('None', 7164), ('TW', 129)]
FIELD_40: 10 elements, tops 4: [('None', 12203), ('unknown', 7762), ('1', 3919), ('02 05 08 11', 57)]
FIELD_41: 6 elements, tops 4: [('I', 10343), ('unknown', 7762), ('V', 3878), ('II', 897)]
FIELD_42: 3 elements, tops 4: [('Zezo', 16116), ('unknown', 7762), ('One', 122)]
FIELD_43: 7 elements, tops 4: [('None', 15288), ('unknown', 7762), ('C', 512), ('B', 294)]
FIELD_44: 4 elements, tops 4: [('One', 11898), ('unknown', 7762), ('Two', 4312), ('None', 28)]
FIELD_45: 6 elements, tops 4: [('1', 10413), ('unknown', 7762), ('2', 2874), (1.0, 2334)]
FIELD_46: 2 elements, tops 4: [(0, 14375), (1, 9625)]
FIELD_47: 2 elements, tops 4: [(True, 14035), (False, 9965)]
FIELD_48: 2 elements, tops 4: [(True, 16639), (False, 7361)]
FIELD_49: 2 elements, tops 4: [(True, 21075), (False, 2925)]
FIELD_50: 10 elements, tops 4: [(29.77, 14252), ('unknown', 7762), (60.946000000000005, 675), (63.293, 467)]
min: 0.0, max: 71.0, mean 32.17033333333333, median 31.0, std 6.99402898244422
min: 6.0, max: 89.0, mean 32.267, median 31.0, std 7.524160188427086
min: 0.0, max: 433.0, mean 35.2565, median 23.0, std 47.055923841556734
min: 4.413, max: 67.633, mean 33.63417983333272, median 33.567499999999995, std 16.081300372324876
min: 30.955, max: 67.634, mean 32.908882083323284, median 30.955, std 7.902256294697767
min: 31.171, max: 67.634, mean 32.97132308331683, median 31.171, std 7.60244243231552
min: 0.0, max: 1.0, mean 0.02508833333333339, median 0.0, std 0.0980677550680178
min: 0.0, max: 1.0, mean 0.10546166666666693, median 0.11, std 0.07062496979931046
min: 0.0, max: 0.92, mean 0.005785416666666642, median 0.0, std 0.026899750999809253
min: 0.0, max: 0.92, mean 0.005586666666666646, median 0.0, std 0.026846524037246484

In [11]:
assert set(db.train_X.columns) - set(db.assets.keys()) == {'id'}

In [12]:
df = db.train_X

In [13]:
import unidecode
import re

df['maCv'] = df.maCv.str.lower()
df['maCv'] = df.maCv.apply(lambda x: re.sub(' +', ' ', unidecode.unidecode(x)))
len(Counter(df['maCv']))

2141

In [21]:
#export
cv_mapper = {'cnv': 'cnv',
             'cong chuc': 'cnv',
             'vien chuc': 'cnv',
             
             'nv': 'nv',
             'nhaon vieon': 'nv',
             'nhon vion': 'nv',
             'n.vien': 'nv',
             'phong vien': 'nv',
             'van thu': 'nv',
             'nha vien': 'nv', 
             'giam dinh vien': 'nv',
             'giao dich vien': 'nv',
             'huong dan vien': 'nv',
             'dieu hanh': 'nv',
             'tong dai vien': 'nv',
             'thu ngan': 'nv',
             'lai ': 'lai xe',
             'tai xe': 'lai xe', 
             
             'ke toan': 'ke toan',
             
             'cong nhan': 'cong nhan',
             'cnhan': 'cong nhan',
             'coong nhaon': 'cong nhan',
             'con gnhan': 'cong nhan',
             'cn.': 'cong nhan',
             'c.n': 'cong nhan',
             'cn': 'cong nhan',
             'van hanh': 'cong nhan',
             'thanh hinh': 'cong nhan',
             'bao tri': 'cong nhan',
             'boc xep': 'cong nhan',
             'cao mu': 'cong nhan',
             'gia cong': 'cong nhan',
             'bao tri': 'cong nhan',
             'bao tri': 'cong nhan',
             'lao dong': 'cong nhan',
             'tu van': 'cong nhan', 
             'tap vu': 'cong nhan', 
             'thu cong': 'cong nhan', 
             'dong goi': 'cong nhan',
             'bao mau': 'cong nhan',
             'ban hang': 'cong nhan',
             'giao hang': 'cong nhan',
             'cong nghiep': 'cong nhan',
             'cap duong':'cong nhan',
             'phet keo': 'cong nhan',
             'quan ly' : 'quan ly',
             'quan doc': 'quan ly',
             'quan li' : 'quan ly',
             'chuyen vien': 'chuyen vien',
             'nhan vien': 'nhan vien',
             'bac si': 'bac si',
             'bac sy': 'bac si',
             'dieu duong': 'dieu duong',
             'y ta': 'y ta',
             'ho ly': 'ho ly',
             'ho sinh': 'ho sinh',
             'y si': 'y si',
             'y sy': 'y si',
             'duoc sy': 'duoc sy',
             'duoc si': 'duoc si',
             'trinh duoc vien': 'trinh duoc vien',
             'giao vien': 'giao vien',
             'gv': 'giao vien',
             'giang vien': 'giao vien',
             'hieu pho': 'giao vien',
             'gioo vion': 'giao vien',
             'hieu truong': 'giao vien',
             
             'chu tich': 'chu tich',
             'can bo':'can bo',
             'cb': 'can bo',
             'can su': 'can bo',
             'dang uy':'can bo',
             'uy vien':'can bo',
             'cong an':'can bo',
             'xa doi':'can bo',
             'bi thu': 'bi thu',
             'bi tu': 'bi thu',
             
             'ky su': 'ky su',
             'kien truc su': 'ky su',
             'thuy thu': 'ky su',
             'thuyen vien': 'ky su',
             
             'tho': 'tho',
             'sua chua': 'tho',
             'ky thuat': 'tho',
             'trung cap': 'tho',
             'co khi': 'tho',
             'bep truong': 'tho',
             
             'to truong': 'to truong',
             'to pho': 'to truong',
             'giam sat': 'to truong',
             'pho phong': 'to truong',
             'giam doc': 'giam doc',
             
             'thu kho': 'thu kho',
             'thu? kho': 'thu kho',
             'thu quy': 'thu kho',
             'bao ve': 'bao ve',
             'b. ve': 'bao ve',
             'b.ve': 'bao ve',
             'bao ve': 'bao ve',
            
             'tro ly': 'tro ly',
             'thu ky': 'tro ly',
             'phu viec': 'phu viec',
             'phuc vu' : 'phu viec',
             'phu': 'phu viec',
             'may': 'cong nhan',
             'hoa chat': 'cong nhan'}

In [15]:
for k, v in cv_mapper.items():
    df['maCv'] = df.maCv.apply(lambda x: v if k in x else x)
len(Counter(df['maCv']))

185

In [16]:
Counter([x for x in df['maCv'] if x not in cv_mapper.values()])

Counter({'unknown': 7763,
         'none': 10532,
         'kiem giay': 1,
         'phan tich cong doan': 1,
         'xu ly': 1,
         'tram pho': 1,
         'phan co': 1,
         'pho truong phong': 1,
         'btd tncshcm': 1,
         'dien vien': 1,
         'thiet ke': 1,
         'p.xnk': 1,
         'truong ca xa': 1,
         'co nuoi': 1,
         'kiem hang': 1,
         'luu hoa cac san pham cao su': 2,
         'dung bep': 1,
         'tiep thi': 1,
         'cua hang truong': 3,
         'phan loai kiem tra san pham': 1,
         'undefined': 13,
         'mau dich vien': 1,
         'bien che dac biet': 1,
         'dai dien tieu thu ii': 2,
         '0': 1,
         'loi xe': 1,
         'ktv so cap': 1,
         'truong phong kinh doanh': 1,
         'dich vu': 1,
         'ktv hoa nghiem': 1,
         'kiem pham': 1,
         'chuyen dung': 1,
         'kcs': 2,
         'bep chinh': 1,
         'operator': 2,
         'lap rap': 2,
         'lay dau': 1,
         'go dan 2': 1,
         'cung nhon': 3,
         'kiem tra chat luong': 1,
         'truong nhom kinh doanh': 1,
         'lap trinh vien': 2,
         'dien vien mua doan nghe thuat tong hop': 1,
         '10958': 1,
         'trai vai': 1,
         'truong tram y te xa que lam': 1,
         'bs. truong pk': 1,
         '135': 1,
         'cd duoc': 1,
         'nau an': 1,
         'cung nhon ki?m hang': 1,
         'vn.5061': 1,
         'hanh chanh tiep tan': 1,
         'ldpt': 3,
         'thuyen truong': 1,
         'quan tri vien du lieu': 1,
         'pho chanh van phong': 1,
         'dao tao': 1,
         'chi huy pho': 1,
         'tiep vien': 2,
         'tram truong': 1,
         'truong th thanh hung': 1,
         'khuyen nong': 1,
         '5339': 1,
         'techno-commercial executive': 1,
         'kiem soat vien': 3,
         'chi huy truong quan su': 4,
         'xuong 1': 1,
         'giao nhan': 2,
         'k? thu?t vion': 1,
         'hoan tat': 1,
         'me technician trainee': 1,
         'chuyen 06': 1,
         'chuan bi lieu': 1,
         '2853': 1,
         'kiem lam vien tc': 1,
         'truong tt': 1,
         'kinh doanh': 6,
         'tram nghien': 1,
         'dau lo say b1': 1,
         'doi truong doi thi cong': 1,
         'san xuat noi dung': 1,
         'senior supervisor partnership distribution': 1,
         'pho t khoa': 1,
         'kiem diich vien dong thuc vat bac 1': 1,
         'truong quay': 1,
         'thanh tra': 1,
         '2983': 1,
         'thieu chuc danh tu du lieu 3s': 3,
         'that day': 1,
         'cod': 2,
         'tin dung': 1,
         'dia chinh - xay dung': 2,
         '1020883': 1,
         'p.ql': 1,
         '147': 1,
         'thuong truc': 1,
         'pha che': 1,
         'ks ql dat dai': 1,
         'duoc ta': 1,
         'ddth': 1,
         'nt cat bo': 1,
         'xuong nhuom': 1,
         'han dien': 1,
         'hoc vien san xuat vung 1': 1,
         'truong khoa duoc can lam sang': 1,
         'doi pho san xuat': 1,
         'pho truong ban dan van': 1,
         'tia bien': 1,
         'cham soc': 2,
         'thuc tap sinh thuong mai': 1,
         'scan mau': 1,
         'thiet ke thiet ke': 1,
         'ho chi minh': 1,
         'kiem hoa': 1,
         'ep kim vieng': 1,
         'uy nhiem thu thue': 1,
         'truong ca': 1,
         'truong phong cham soc khach hang': 1,
         'x9-vat tu sat': 1,
         'ho tro san xuat': 1,
         'kiem ngan vien': 1,
         '1020096': 1,
         'cc. dcxxd': 1,
         'mai nhan mat da lang da': 1,
         'ktv': 1,
         'pho chi huy truong quan su': 1,
         'ep da': 1,
         'dau bep': 2,
         'hop dong thu': 1,
         'p.gdoc': 1,
         'cong tac tai vung tau': 1,
         'tksl trong k.truong mo': 1,
         'khieng khuon': 1,
         'pho chu quan p.hanh chinh': 1,
         'mai': 1,
         'kiem tra vien': 1,
         'nghien cuu vien 85% bac 1/9': 1,
         'truong ca - v01 - tp. ho chi minh': 1,
         'mai da': 1,
         'che tac vien': 1,
         'truong bo phan': 1,
         'dong dinh': 1,
         'ap suat': 1,
         'pho trai': 1,
         'pho chu nhiem': 1,
         'xuong soi': 1,
         'lo truong': 1,
         'ho tich - pca': 1,
         'thao tac vien': 1,
         'tri lieu cs': 1,
         'qc point 7': 1,
         'cat co': 1,
         'tcxd': 1,
         'truong phong': 1,
         'hoist': 1,
         'truong tram': 1})

In [22]:
!python notebook2script.py 01_load_data.ipynb

Converted 01_load_data.ipynb to exp/nb_01.py

In [18]:
ls

01_load_data.ipynb     04_fast_ai_v1.ipynb      data/    notebook2script.py*
02_gini_score.ipynb    05_enrich_feature.ipynb  exp/     README.md
03_simple_model.ipynb  06_train_model.ipynb     models/